name: CI

# This workflow tests that the APPLICATION works correctly
# It does NOT test if challenges are solved (those tests are in tests/Solutions/)
# Challenge code is intentionally broken for users to fix

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2, 8.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, mysql, pdo_mysql
        coverage: xdebug

    - name: Copy environment file
      run: cp .env.example .env

    - name: Install dependencies
      run: |
        composer update --prefer-dist --no-interaction --no-progress
        npm install

    - name: Generate application key
      run: php artisan key:generate

    - name: Create SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite
        chmod 777 database/database.sqlite

    - name: Set up database
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ${{ github.workspace }}/database/database.sqlite
      run: |
        php artisan migrate:fresh --force
        php artisan db:seed --force

    - name: Build assets
      run: npm run build

    - name: Run PHPStan
      run: composer phpstan

    - name: Run Pint
      run: ./vendor/bin/pint --test

    - name: Run tests (Unit & Feature only)
      run: |
        # This runs only Unit and Feature tests (excludes Solutions tests)
        # Solutions tests verify challenge solutions and will fail until challenges are fixed
        # Note: Coverage requirement removed as challenge code is intentionally broken for users to fix
        php artisan test --exclude-group=solutions

    - name: Upload coverage reports to Codecov
      if: false  # Disabled: Challenge code is intentionally broken, coverage metrics not applicable
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false